version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twine
    versions:
    - 3.4.0
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
- package-ecosystem: npm
  directory: "/arctic/static/arctic"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.13
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.8
