[tool.black]
line-length = 79

exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | (.)+\.egg-info
  | static
  | migrations
  | tests
  | \project_template
)/
'''
