# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/font-awesome/scss"
    - "node_modules/"
    - "src/assets/scss/"
    - "node_modules/bootstrap/scss/"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries required by Bootstrap
    - "node_modules/jquery/dist/jquery.min.js"
    - "node_modules/popper.js/dist/umd/popper.js"
    - "node_modules/bootstrap/dist/js/bootstrap.js"

    # Arctic JS deps
    - "node_modules/jquery.are-you-sure/jquery.are-you-sure.js"
    - "node_modules/air-datepicker/dist/js/datepicker.js"
    - "node_modules/air-datepicker/dist/js/i18n/datepicker.en.js"
    - "node_modules/selectize/dist/js/standalone/selectize.js"
    - "node_modules/sortablejs/Sortable.js"
    - "node_modules/iframe-resizer/js/iframeResizer.js"
    - "node_modules/moment/min/moment.min.js"

    # Paths to your own project code are here
    - "src/assets/js/utils/helpers.js"
    - "src/assets/js/components/toggle_form.js"
    - "src/assets/js/components/widgets.js"
    - "src/assets/js/components/file_input.js"
    - "src/assets/js/components/float_label.js"
    - "src/assets/js/components/modal.js"
    - "src/assets/js/components/csv_export.js"
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
