# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Role'),
        ),
    ]
